server:
  port: 8088

spring:
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     username: root
     url: jdbc:mysql://localhost:3306/fixeddepositsdb
     password: smiles@1221
   jpa:
     database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
     hibernate:
       ddl-auto: update
       show-sql: true
   application:
     name: FIXED-DEPOSIT-SERVICE
